import type { AlbumThemeDisplay, StoryThemeDisplay } from "@/types/themes";

export const FALLBACK_STORY_THEMES: StoryThemeDisplay[] = [
  {
    id: "fallback-princesa-carnaval",
    slug: "princesa-carnaval",
    title: "Princesa do Carnaval",
    description: "Uma aventura mágica pelos desfiles mais coloridos do Brasil",
    color: "from-pink-400 to-pink-600",
    iconKey: "crown",
    emoji: "👑",
    image: "/images/princess-carnival.jpg",
  },
  {
    id: "fallback-heroi-futebol",
    slug: "heroi-futebol",
    title: "Herói do Futebol",
    description: "Conquiste a Copa dos Sonhos com muita garra e talento",
    color: "from-green-500 to-green-700",
    iconKey: "flame",
    emoji: "⚽",
    image: "/images/soccer-hero.jpg",
  },
  {
    id: "fallback-iara-sereia",
    slug: "iara-sereia",
    title: "Iara Sereia",
    description: "Explore os rios encantados da floresta amazônica",
    color: "from-cyan-400 to-teal-600",
    iconKey: "waves",
    emoji: "🧜‍♀️",
    image: "/images/iara-mermaid.jpg",
  },
  {
    id: "fallback-saci-perere",
    slug: "saci-perere",
    title: "Saci-Pererê",
    description: "Travessuras e aventuras pelo folclore brasileiro",
    color: "from-red-500 to-red-700",
    iconKey: "sparkles",
    emoji: "🔥",
    image: "/images/saci-perere.jpg",
  },
  {
    id: "fallback-explorador-amazonia",
    slug: "explorador-amazonia",
    title: "Explorador da Amazônia",
    description: "Descubra os segredos da maior floresta do mundo",
    color: "from-emerald-500 to-green-700",
    iconKey: "tree",
    emoji: "🌿",
    image: "/images/amazon-explorer.jpg",
  },
  {
    id: "fallback-anjo-guardiao",
    slug: "anjo-guardiao",
    title: "Anjo Guardião",
    description: "Uma jornada celestial de amor e proteção",
    color: "from-sky-400 to-blue-500",
    iconKey: "bird",
    emoji: "👼",
    image: "/images/angel-guardian.jpg",
  },
  {
    id: "fallback-festa-junina",
    slug: "festa-junina",
    title: "Festa Junina",
    description: "Quadrilha, fogueira e muita alegria caipira",
    color: "from-amber-400 to-orange-500",
    iconKey: "music",
    emoji: "🎉",
    image: "/images/festa-junina.jpg",
  },
  {
    id: "fallback-super-heroi",
    slug: "super-heroi",
    title: "Super-Herói Brasileiro",
    description: "Poderes especiais para proteger o Brasil",
    color: "from-yellow-400 to-green-600",
    iconKey: "shield",
    emoji: "🦸",
    image: "/images/super-hero.jpg",
  },
];

export const FALLBACK_ALBUM_THEMES: AlbumThemeDisplay[] = [
  {
    id: "fallback-baby-minimal",
    slug: "baby-minimal",
    name: "Ternura",
    description: "Suave e delicado",
    colors: {
      primary: "from-pink-100 via-pink-50 to-pink-100",
      secondary: "bg-pink-50/80",
      accent: "bg-carnival-pink",
      text: "text-carnival-pink",
    },
    pattern: "minimal",
  },
  {
    id: "fallback-boho-chic",
    slug: "boho-chic",
    name: "Aconchego",
    description: "Tons quentes",
    colors: {
      primary: "from-amber-100 via-orange-50 to-amber-100",
      secondary: "bg-amber-50/80",
      accent: "bg-carnival-gold",
      text: "text-carnival-gold",
    },
    pattern: "boho",
  },
  {
    id: "fallback-carnival-suave",
    slug: "carnival-suave",
    name: "Alegria",
    description: "Colorido e vibrante",
    colors: {
      primary: "from-pink-100 via-pink-50 to-cyan-100",
      secondary: "bg-pink-50/80",
      accent: "bg-carnival-turquoise",
      text: "text-carnival-turquoise",
    },
    pattern: "carnival",
  },
  {
    id: "fallback-natureza",
    slug: "natureza",
    name: "Serenidade",
    description: "Verde e tranquilo",
    colors: {
      primary: "from-emerald-100 via-green-50 to-teal-100",
      secondary: "bg-emerald-50/80",
      accent: "bg-carnival-green",
      text: "text-carnival-green",
    },
    pattern: "nature",
  },
  {
    id: "fallback-encantado",
    slug: "encantado",
    name: "Magia",
    description: "Encantado",
    colors: {
      primary: "from-violet-100 via-purple-50 to-pink-100",
      secondary: "bg-violet-50/80",
      accent: "bg-carnival-coral",
      text: "text-carnival-coral",
    },
    pattern: "enchanted",
  },
  {
    id: "fallback-classico-elegante",
    slug: "classico-elegante",
    name: "Elegância",
    description: "Sofisticado",
    colors: {
      primary: "from-stone-100 via-neutral-50 to-stone-100",
      secondary: "bg-stone-50/80",
      accent: "bg-stone-400",
      text: "text-stone-600",
    },
    pattern: "classic",
  },
];
